services:
  api:
    container_name: map-storage-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/map_storage_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: unless-stopped

  postgres-db:
    container_name: map-storage-backend-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: map_storage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./infrastructure/db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db:
    driver: local
  gradle-cache: