services:
  api:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://map-storage-backend-postgres-db-1/map_storage_db


  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=map_storage_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./infrastructure/db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  db:
    driver: local